<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php
        /* $_GLOBALS 
        Contains a reference to every variable which is currently available within 
        the global scope of the script.
        */
        /* $_SERVER 
        containing information such as headers, paths, and script locations.
        The entries in this array are created by the web server.
        */
        /* $_GET
        An associative array of variables passed to the current script via the HTTP GET method.
        */
        /* $_POST 
        An associative array of variables passed to the current script via the HTTP POST method.
        */
        /* $_FILES
        An associative array of items uploaded to the current script via the HTTP POST method.
        */
        /* $_REQUEST
        An associative array consisting of the contents of $_GET, $_POST, and $_COOKIE
        *?
        /* $_COOKIE 
        An associative array of variables passed to the current script via HTTP cookies.
        */
        /* $_SESSION
        An associative array containing session variables available to the current script.
        */
        /* $_PHP_SELF
        A string containing PHP script file name in which it is called.
        */
        /* php_errormsg 
        $php_errormsg is a variable containing the text of the last error message generated by PHP.
        */
        
    ?>
</body>
</html>